/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedVIdRouteImport } from './routes/_authenticated/v.$id'
import { Route as AuthenticatedVIdResultsAttemptIdRouteImport } from './routes/_authenticated/v.$id.results.$attemptId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVIdRoute = AuthenticatedVIdRouteImport.update({
  id: '/v/$id',
  path: '/v/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVIdResultsAttemptIdRoute =
  AuthenticatedVIdResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => AuthenticatedVIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new': typeof AuthenticatedNewRoute
  '/v/$id': typeof AuthenticatedVIdRouteWithChildren
  '/v/$id/results/$attemptId': typeof AuthenticatedVIdResultsAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new': typeof AuthenticatedNewRoute
  '/v/$id': typeof AuthenticatedVIdRouteWithChildren
  '/v/$id/results/$attemptId': typeof AuthenticatedVIdResultsAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/v/$id': typeof AuthenticatedVIdRouteWithChildren
  '/_authenticated/v/$id/results/$attemptId': typeof AuthenticatedVIdResultsAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/new'
    | '/v/$id'
    | '/v/$id/results/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/new'
    | '/v/$id'
    | '/v/$id/results/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/new'
    | '/_authenticated/v/$id'
    | '/_authenticated/v/$id/results/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/v/$id': {
      id: '/_authenticated/v/$id'
      path: '/v/$id'
      fullPath: '/v/$id'
      preLoaderRoute: typeof AuthenticatedVIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/v/$id/results/$attemptId': {
      id: '/_authenticated/v/$id/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/v/$id/results/$attemptId'
      preLoaderRoute: typeof AuthenticatedVIdResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedVIdRoute
    }
  }
}

interface AuthenticatedVIdRouteChildren {
  AuthenticatedVIdResultsAttemptIdRoute: typeof AuthenticatedVIdResultsAttemptIdRoute
}

const AuthenticatedVIdRouteChildren: AuthenticatedVIdRouteChildren = {
  AuthenticatedVIdResultsAttemptIdRoute: AuthenticatedVIdResultsAttemptIdRoute,
}

const AuthenticatedVIdRouteWithChildren =
  AuthenticatedVIdRoute._addFileChildren(AuthenticatedVIdRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedVIdRoute: typeof AuthenticatedVIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedVIdRoute: AuthenticatedVIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
